name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
<<<<<<< HEAD
      run: swift package init --type executable
=======
      run: swift build -v
>>>>>>> 0d1dad4 (Create swift.yml)
    - name: Run tests
      run: swift test -v
